site_name: template
site_author: YourName
site_description: >-
  This is the template package!
nav:
  - Home: index.md
  - Overview:
      - example_docs/intro/why.md
  - Setup:
      - example_docs/setup/prep.md
      - example_docs/setup/name.md
      - example_docs/setup/basics.md
  - Installation:
      - example_docs/installation/pyproject.md
      - example_docs/installation/install.md
  - Code:
      - example_docs/code/source.md
  - Documentation:
      - example_docs/mkdocs/docs.md
  - Uploading to GitHub:
      - example_docs/wrapup/commits.md
  - Continuous Integration:
      - example_docs/ci/tests.md
      - example_docs/ci/workflows.md
  - Miscellaneous:
      - example_docs/other/misc.md
  - About:
      - example_docs/about/changelog.md
      - example_docs/about/conduct.md
      - example_docs/about/license.md
  - Code Documentation: reference/

repo_url: https://github.com/Quantum-Accelerators/template/
edit_uri: blob/main/docs/

theme:
  features:
    - content.action.edit
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - content.tabs.link
    - content.tooltips
    - navigation.footer
    - navigation.path
    - navigation.tracking
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.suggest
    - search.share
    - header.autohide
    - toc.follow
  name: material
  palette:
    primary: orange
    scheme: slate

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg ""
      emoji_index: !!python/name:materialx.emoji.twemoji ""
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format ""
          name: mermaid
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - autorefs
  - social
  - offline
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          import:
            - https://docs.python.org/3/objects.inv
            - https://numpy.org/doc/stable/objects.inv
          options:
            docstring_style: numpy
            docstring_section_style: list
            separate_signature: true
            merge_init_into_class: true
            docstring_options:
              ignore_init_summary: true
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
